# Generated by Django 4.2.5 on 2023-11-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('car_brand', models.CharField(max_length=128)),
                ('car_model', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('mech', models.EmailField(max_length=254)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
