# Generated by Django 4.2.5 on 2023-11-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('date', models.DateTimeField()),
                ('car_brand', models.CharField(max_length=128)),
                ('car_model', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=128)),
                ('commune', models.CharField(max_length=128)),
                ('mech', models.BooleanField()),
                ('confirmed', models.BooleanField()),
            ],
        ),
    ]
