# Generated by Django 4.2.5 on 2023-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='mech',
            field=models.EmailField(max_length=254),
        ),
    ]
