# Generated by Django 4.2.5 on 2023-11-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsMech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mech', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
